### ISSUE TITLE
Verse Tagging

### ISSUE THREAD

**Issue by donald-john** [imdonaldjohn/woodworm#3]
Call WW on a block of text containing bible verses (eg. Deuteronomy 12:4) and WW highlights it and displays an overlay with the verse text from labs.bible.org. Onclick, navigate to Lumina.

**Comment by donald-john** [comment]
There will need to be a considerable delay on hover so that the api isn't pinged continuously. Perhaps after a second or two display a loading animation, THEN make the call so the user knows it's retrieving before it actually makes the call in case they want to move the mouse.

**Comment by imdonaldjohn** [comment]
deprecated - closing
